import json
import sys
from pathlib import Path

from PIL import Image
from PySide6.QtCore import (
    Qt, QThread, QUrl, Signal, QFile, QIODevice, QSettings,
)
from PySide6.QtGui import QDesktopServices, QIcon
from PySide6.QtWidgets import (
    QApplication,
    QCheckBox,
    QComboBox,
    QFileDialog,
    QFormLayout,
    QGroupBox,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QMainWindow,
    QMessageBox,
    QProgressBar,
    QPushButton,
    QSpinBox,
    QTextEdit,
    QVBoxLayout,
    QWidget,
)

import qtawesome as qta

from core.renderer import AdobeSpritemapRenderer

import core.resources

_INVALID_CHARS = '<>:"/\\|?*'
_RESERVED_NAMES = {
    "CON",
    "PRN",
    "AUX",
    "NUL",
    *(f"COM{i}" for i in range(1, 10)),
    *(f"LPT{i}" for i in range(1, 10)),
}


def sanitize_filename(name: str) -> str:
    cleaned = "".join("_" if ch in _INVALID_CHARS else ch for ch in name)
    cleaned = cleaned.strip().rstrip(". ")
    if not cleaned:
        return "unnamed"
    if cleaned.upper().split(".")[0] in _RESERVED_NAMES:
        cleaned = f"_{cleaned}"
    return cleaned


class GifWriter:
    @staticmethod
    def save(
        frames: list,
        gif_path: Path,
        duration: int,
        loop: int,
        disposal: int,
    ) -> None:
        if not frames:
            return
        first, *rest = frames
        first.save(
            gif_path,
            save_all=True,
            append_images=rest,
            duration=duration,
            loop=loop,
            disposal=disposal,
            comment="GIF Generated by: Spritemap to GIF",
        )


def validate_animation_json(path: Path) -> None:
    try:
        with path.open("r", encoding="utf-8-sig") as fh:
            data = json.load(fh)
    except json.JSONDecodeError as exc:
        raise ValueError(f"{path.name} is not valid JSON: {exc}") from exc
    if not isinstance(data, dict):
        raise ValueError(f"{path.name} must contain a JSON object at the top level.")


class DropLineEdit(QLineEdit):
    def __init__(self, file_mode: str = "file", extensions: tuple = (), parent=None):
        super().__init__(parent)
        self.file_mode = file_mode
        self.extensions = tuple(e.lower() for e in extensions)
        self.setAcceptDrops(True)

    def dragEnterEvent(self, event):
        if event.mimeData().hasUrls():
            urls = event.mimeData().urls()
            if len(urls) == 1 and self._is_valid_path(urls[0].toLocalFile()):
                event.acceptProposedAction()
                self._set_drag_style(True)
                return
        event.ignore()

    def dragLeaveEvent(self, event):
        self._set_drag_style(False)
        super().dragLeaveEvent(event)

    def dropEvent(self, event):
        self._set_drag_style(False)
        if event.mimeData().hasUrls():
            urls = event.mimeData().urls()
            if len(urls) == 1:
                path = urls[0].toLocalFile()
                if self._is_valid_path(path):
                    self.setText(path)
                    event.acceptProposedAction()
                    return
        event.ignore()

    def _is_valid_path(self, path: str) -> bool:
        if not path:
            return False
        p = Path(path)
        if self.file_mode == "folder":
            return p.is_dir()
        if not p.is_file():
            return False
        if self.extensions and p.suffix.lower() not in self.extensions:
            return False
        return True

    def _set_drag_style(self, active: bool):
        self.setProperty("dragActive", active)
        self.style().unpolish(self)
        self.style().polish(self)


class ExportWorker(QThread):
    progress = Signal(int, int, str)
    log = Signal(str)
    finished_export = Signal(str, str)
    error = Signal(str)

    def __init__(
        self,
        animation_path: str,
        spritemap_json_path: str,
        atlas_image_path: str,
        output_dir: str,
        duration: int,
        loop: int,
        disposal: int,
        filter_single_frame: bool,
        filter_unused_symbols: bool,
        root_animation_only: bool,
        use_source_fps: bool = False,
    ):
        super().__init__()
        self.animation_path = animation_path
        self.spritemap_json_path = spritemap_json_path
        self.atlas_image_path = atlas_image_path
        self.output_dir = output_dir
        self.duration = duration
        self.loop = loop
        self.disposal = disposal
        self.filter_single_frame = filter_single_frame
        self.filter_unused_symbols = filter_unused_symbols
        self.root_animation_only = root_animation_only
        self.use_source_fps = use_source_fps
        self._cancel = False

    def cancel(self):
        self._cancel = True

    def run(self):
        renderer = None
        try:
            try:
                validate_animation_json(Path(self.animation_path))
                validate_animation_json(Path(self.spritemap_json_path))
            except ValueError as exc:
                self.error.emit(str(exc))
                return

            self.log.emit("Loading animation document...")
            renderer = AdobeSpritemapRenderer(
                animation_path=self.animation_path,
                spritemap_json_path=self.spritemap_json_path,
                atlas_image_path=self.atlas_image_path,
                filter_single_frame=self.filter_single_frame,
                filter_unused_symbols=self.filter_unused_symbols,
                root_animation_only=self.root_animation_only,
            )

            duration = self.duration
            if self.use_source_fps:
                fps = getattr(renderer, "frame_rate", 0) or 0
                if fps > 0:
                    duration = max(10, round(1000 / fps))
                    self.log.emit(f"Using source framerate: {fps:g} fps -> {duration} ms")
                else:
                    self.log.emit(
                        f"Source framerate not available; falling back to {duration} ms"
                    )

            root_name = renderer.get_root_animation_name() or "spritemap"
            output_path = Path(self.output_dir) / sanitize_filename(root_name)
            output_path.mkdir(parents=True, exist_ok=True)
            self.log.emit(f"Created output folder: {output_path}")

            animations = list(renderer.iter_animations())
            total = len(animations)
            if total == 0:
                self.error.emit("No animations found to export.")
                return

            exported = 0
            failures = 0
            seen_names: dict = {}
            for index, (name, frame_iterator) in enumerate(animations, start=1):
                if self._cancel:
                    self.log.emit("Export cancelled by user.")
                    return

                base_name = sanitize_filename(name)
                count = seen_names.get(base_name, 0)
                seen_names[base_name] = count + 1
                safe_name = base_name if count == 0 else f"{base_name}_{count}"

                self.progress.emit(index, total, safe_name)
                self.log.emit(f"Rendering '{safe_name}'...")

                frames = []
                try:
                    for _, frame_image, _ in frame_iterator:
                        if self._cancel:
                            self.log.emit("Export cancelled by user.")
                            return
                        frames.append(frame_image)

                    if not frames:
                        self.log.emit(f"  Skipping '{safe_name}' (no frames).")
                        continue

                    gif_path = output_path / f"{safe_name}.gif"
                    GifWriter.save(
                        frames,
                        gif_path,
                        duration=duration,
                        loop=self.loop,
                        disposal=self.disposal,
                    )
                    exported += 1
                    self.log.emit(f"  Saved: {gif_path.name}")
                except Exception as exc:
                    failures += 1
                    self.log.emit(f"  ERROR on '{safe_name}': {exc}")
                finally:
                    for frame in frames:
                        try:
                            frame.close()
                        except Exception:
                            pass
                    frames.clear()

            summary = f"Export complete. {exported} GIF(s) saved to:\n{output_path}"
            if failures:
                summary += f"\n\n{failures} animation(s) failed — see log."
            self.finished_export.emit(summary, str(output_path))
        except Exception as exc:
            self.error.emit(str(exc))
        finally:
            if renderer is not None:
                renderer.close()


class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Spritemap to GIF")
        self.setWindowIcon(QIcon(":ui/icon.ico"))
        self.setMinimumSize(750, 795)
        self.resize(750, 795)
        self.worker = None
        self._last_output_dir = None
        self.settings = QSettings("Spritemap To Gif", "Persistence")

        self._build_ui()
        self._load_settings()
        self._apply_styles()
        self._center_window()

    def _center_window(self):
        screen = QApplication.primaryScreen().availableGeometry()
        window_frame = self.frameGeometry()
        window_frame.moveCenter(screen.center())
        self.move(window_frame.topLeft())

    def _build_ui(self):
        central = QWidget()
        self.setCentralWidget(central)
        main_layout = QVBoxLayout(central)
        main_layout.setContentsMargins(16, 16, 16, 16)
        main_layout.setSpacing(12)

        self.files_group = QGroupBox("Input Files")
        files_layout = QFormLayout(self.files_group)
        files_layout.setLabelAlignment(Qt.AlignRight)

        self.animation_spritemap_edit = DropLineEdit(
            file_mode="file", extensions=(".json",)
        )
        self.animation_spritemap_edit.setPlaceholderText("animation.json (drag & drop)")
        files_layout.addRow(
            self._icon_label("fa5s.file-code", "Animation JSON:"),
            self._file_row(self.animation_spritemap_edit, self._pick_animation),
        )

        self.spritemap_code_edit = DropLineEdit(file_mode="file", extensions=(".json",))
        self.spritemap_code_edit.setPlaceholderText("spritemap.json (drag & drop)")
        files_layout.addRow(
            self._icon_label("fa5s.file-code", "Spritemap JSON:"),
            self._file_row(self.spritemap_code_edit, self._pick_spritemap),
        )

        self.spritemap_image_edit = DropLineEdit(file_mode="file", extensions=(".png",))
        self.spritemap_image_edit.setPlaceholderText("spritemap.png (drag & drop)")
        files_layout.addRow(
            self._icon_label("fa5s.image", "Spritemap PNG:"),
            self._file_row(self.spritemap_image_edit, self._pick_atlas),
        )

        main_layout.addWidget(self.files_group)

        self.output_group = QGroupBox("Output")
        output_layout = QFormLayout(self.output_group)
        output_layout.setLabelAlignment(Qt.AlignRight)

        self.output_edit = DropLineEdit(file_mode="folder")
        self.output_edit.setPlaceholderText("Drop folder here or choose...")
        output_layout.addRow(
            self._icon_label("fa5s.folder", "Output Folder:"),
            self._file_row(self.output_edit, self._pick_output),
        )
        main_layout.addWidget(self.output_group)

        self.settings_group = QGroupBox("GIF Settings")
        settings_layout = QFormLayout(self.settings_group)
        settings_layout.setLabelAlignment(Qt.AlignRight)

        self.duration_spin = QSpinBox()
        self.duration_spin.setRange(10, 10000)
        self.duration_spin.setValue(42)
        self.duration_spin.setSuffix(" ms")
        settings_layout.addRow(
            self._icon_label("fa5s.clock", "Frame Duration:"), self.duration_spin
        )

        self.use_source_fps_check = QCheckBox("Use source framerate")
        self.use_source_fps_check.setChecked(False)
        self.use_source_fps_check.setToolTip(
            "Derive frame duration from the animation's declared framerate "
            "instead of the value above."
        )
        self.use_source_fps_check.toggled.connect(
            lambda checked: self.duration_spin.setEnabled(not checked)
        )
        settings_layout.addRow(
            self._icon_label("fa5s.tachometer-alt", "Timing:"),
            self.use_source_fps_check,
        )

        self.loop_spin = QSpinBox()
        self.loop_spin.setRange(0, 100)
        self.loop_spin.setValue(0)
        self.loop_spin.setToolTip("0 = infinite loop")
        settings_layout.addRow(
            self._icon_label("fa5s.redo", "Loop Count:"), self.loop_spin
        )

        self.disposal_combo = QComboBox()
        self.disposal_combo.addItem("2 - Restore to background", 2)
        self.disposal_combo.addItem("1 - Do not dispose", 1)
        self.disposal_combo.addItem("3 - Restore to previous", 3)
        self.disposal_combo.setItemData(
            0,
            "Redraw background between frames. Best for most animations.",
            Qt.ToolTipRole,
        )
        self.disposal_combo.setItemData(
            1,
            "Keep previous frame pixels. Can produce ghosting/trails.",
            Qt.ToolTipRole,
        )
        self.disposal_combo.setItemData(
            2,
            "Restore the frame before the last one. Rarely needed.",
            Qt.ToolTipRole,
        )
        settings_layout.addRow(
            self._icon_label("fa5s.trash-alt", "Disposal:"), self.disposal_combo
        )

        main_layout.addWidget(self.settings_group)

        self.options_group = QGroupBox("Export Options")
        options_layout = QVBoxLayout(self.options_group)

        self.filter_single_check = QCheckBox("Filter single-frame animations")
        self.filter_single_check.setChecked(True)
        options_layout.addWidget(self.filter_single_check)

        self.filter_unused_check = QCheckBox("Filter unused symbols")
        self.filter_unused_check.setChecked(False)
        options_layout.addWidget(self.filter_unused_check)

        self.root_only_check = QCheckBox("Root animation only")
        self.root_only_check.setChecked(False)
        options_layout.addWidget(self.root_only_check)

        main_layout.addWidget(self.options_group)

        button_row = QHBoxLayout()
        button_row.setSpacing(8)

        self.export_button = QPushButton(
            qta.icon("fa5s.play", color="#FFFFFF"), "  Export GIFs"
        )
        self.export_button.setObjectName("exportButton")
        self.export_button.setMinimumHeight(40)
        self.export_button.clicked.connect(self._start_export)
        button_row.addWidget(self.export_button, stretch=2)

        self.cancel_button = QPushButton(
            qta.icon("fa5s.stop", color="#FFFFFF"), "  Cancel"
        )
        self.cancel_button.setObjectName("cancelButton")
        self.cancel_button.setMinimumHeight(40)
        self.cancel_button.setEnabled(False)
        self.cancel_button.clicked.connect(self._cancel_export)
        button_row.addWidget(self.cancel_button, stretch=1)

        self.open_folder_button = QPushButton(
            qta.icon("fa5s.folder-open", color="#E0E0E0"), "  Open Output"
        )
        self.open_folder_button.setMinimumHeight(40)
        self.open_folder_button.setEnabled(False)
        self.open_folder_button.clicked.connect(self._open_output_folder)
        button_row.addWidget(self.open_folder_button, stretch=1)

        main_layout.addLayout(button_row)

        self.progress_bar = QProgressBar()
        self.progress_bar.setValue(0)
        self.progress_bar.setTextVisible(True)
        main_layout.addWidget(self.progress_bar)

        self.log_view = QTextEdit()
        self.log_view.setReadOnly(True)
        self.log_view.setPlaceholderText("Export log will appear here...")
        self.log_view.document().setMaximumBlockCount(5000)
        main_layout.addWidget(self.log_view, stretch=1)

    def _icon_label(self, icon_name: str, text: str) -> QWidget:
        container = QWidget()
        container.setObjectName("iconLabelContainer")
        layout = QHBoxLayout(container)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(6)
        icon_label = QLabel()
        icon_label.setPixmap(qta.icon(icon_name, color="#90CAF9").pixmap(16, 16))
        layout.addWidget(icon_label)
        layout.addWidget(QLabel(text))
        return container

    def _file_row(self, line_edit: QLineEdit, handler) -> QWidget:
        container = QWidget()
        layout = QHBoxLayout(container)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(6)
        layout.addWidget(line_edit)

        button = QPushButton(qta.icon("fa5s.folder-open", color="#E0E0E0"), "")
        button.setFixedWidth(36)
        button.setCursor(Qt.PointingHandCursor)
        button.clicked.connect(handler)
        layout.addWidget(button)
        return container

    def _pick_animation(self):
        path, _ = QFileDialog.getOpenFileName(
            self, "Select Animation JSON", "", "JSON Files (*.json);;All Files (*)"
        )
        if path:
            self.animation_spritemap_edit.setText(path)

    def _pick_spritemap(self):
        path, _ = QFileDialog.getOpenFileName(
            self, "Select Spritemap JSON", "", "JSON Files (*.json);;All Files (*)"
        )
        if path:
            self.spritemap_code_edit.setText(path)

    def _pick_atlas(self):
        path, _ = QFileDialog.getOpenFileName(
            self,
            "Select Spritemap Image",
            "",
            "Images (*.png);;All Files (*)",
        )
        if path:
            self.spritemap_image_edit.setText(path)

    def _pick_output(self):
        path = QFileDialog.getExistingDirectory(self, "Select Output Folder")
        if path:
            self.output_edit.setText(path)

    def _load_settings(self):
        for key, edit in (
            ("paths/animation", self.animation_spritemap_edit),
            ("paths/spritemap", self.spritemap_code_edit),
            ("paths/atlas", self.spritemap_image_edit),
            ("paths/output", self.output_edit),
        ):
            value = self.settings.value(key, "")
            if value:
                edit.setText(str(value))

        def _restore_int(key, widget, default):
            try:
                widget.setValue(int(self.settings.value(key, default)))
            except (TypeError, ValueError):
                widget.setValue(default)

        _restore_int("gif/duration", self.duration_spin, 42)
        _restore_int("gif/loop", self.loop_spin, 0)

        def _restore_bool(key, widget, default=False):
            value = self.settings.value(key, default)
            if isinstance(value, str):
                value = value.lower() in {"true", "1", "yes"}
            widget.setChecked(bool(value))

        _restore_bool("gif/use_source_fps", self.use_source_fps_check, False)
        _restore_bool("options/filter_single", self.filter_single_check, True)
        _restore_bool("options/filter_unused", self.filter_unused_check, False)
        _restore_bool("options/root_only", self.root_only_check, False)

        disposal = self.settings.value("gif/disposal", 2)
        try:
            disposal = int(disposal)
        except (TypeError, ValueError):
            disposal = 2
        idx = self.disposal_combo.findData(disposal)
        if idx >= 0:
            self.disposal_combo.setCurrentIndex(idx)

    def _save_settings(self, animation_path, spritemap_path, atlas_path, output_dir):
        self.settings.setValue("paths/animation", str(animation_path))
        self.settings.setValue("paths/spritemap", str(spritemap_path))
        self.settings.setValue("paths/atlas", str(atlas_path))
        self.settings.setValue("paths/output", str(output_dir))
        self.settings.setValue("gif/duration", self.duration_spin.value())
        self.settings.setValue("gif/loop", self.loop_spin.value())
        self.settings.setValue("gif/disposal", self.disposal_combo.currentData())
        self.settings.setValue(
            "gif/use_source_fps", self.use_source_fps_check.isChecked()
        )
        self.settings.setValue(
            "options/filter_single", self.filter_single_check.isChecked()
        )
        self.settings.setValue(
            "options/filter_unused", self.filter_unused_check.isChecked()
        )
        self.settings.setValue(
            "options/root_only", self.root_only_check.isChecked()
        )

    def _start_export(self):
        animation_path = Path(self.animation_spritemap_edit.text().strip())
        spritemap_path = Path(self.spritemap_code_edit.text().strip())
        atlas_path = Path(self.spritemap_image_edit.text().strip())
        output_dir = Path(self.output_edit.text().strip())

        if not all(
            (
                self.animation_spritemap_edit.text().strip(),
                self.spritemap_code_edit.text().strip(),
                self.spritemap_image_edit.text().strip(),
                self.output_edit.text().strip(),
            )
        ):
            QMessageBox.warning(
                self, "Missing Input", "Please fill in all file and folder paths."
            )
            return

        for label, path in (
            ("Animation JSON", animation_path),
            ("Spritemap JSON", spritemap_path),
            ("Spritemap PNG", atlas_path),
        ):
            if not path.is_file():
                QMessageBox.warning(
                    self, "File Not Found", f"{label} not found:\n{path}"
                )
                return

        if not output_dir.is_dir():
            QMessageBox.warning(
                self, "Folder Not Found", f"Output folder not found:\n{output_dir}"
            )
            return

        try:
            validate_animation_json(animation_path)
            validate_animation_json(spritemap_path)
        except ValueError as exc:
            QMessageBox.critical(self, "Invalid Input", str(exc))
            return

        self._save_settings(animation_path, spritemap_path, atlas_path, output_dir)

        self._set_exporting(True)
        self.log_view.clear()
        self.progress_bar.setValue(0)
        self.progress_bar.setMaximum(1)
        self.progress_bar.setFormat("Starting...")
        self.open_folder_button.setEnabled(False)
        self._last_output_dir = None

        self.worker = ExportWorker(
            animation_path=str(animation_path),
            spritemap_json_path=str(spritemap_path),
            atlas_image_path=str(atlas_path),
            output_dir=str(output_dir),
            duration=self.duration_spin.value(),
            loop=self.loop_spin.value(),
            disposal=self.disposal_combo.currentData(),
            filter_single_frame=self.filter_single_check.isChecked(),
            filter_unused_symbols=self.filter_unused_check.isChecked(),
            root_animation_only=self.root_only_check.isChecked(),
            use_source_fps=self.use_source_fps_check.isChecked(),
        )
        self.worker.progress.connect(self._on_progress)
        self.worker.log.connect(self._on_log)
        self.worker.finished_export.connect(self._on_finished)
        self.worker.error.connect(self._on_error)
        self.worker.finished.connect(self.worker.deleteLater)
        self.worker.start()

    def _cancel_export(self):
        if self.worker is not None and self.worker.isRunning():
            self.cancel_button.setEnabled(False)
            self.progress_bar.setFormat("Cancelling after current frame...")
            self.log_view.append("Cancel requested, finishing current frame…")
            self.worker.cancel()

    def _open_output_folder(self):
        if self._last_output_dir and Path(self._last_output_dir).is_dir():
            QDesktopServices.openUrl(QUrl.fromLocalFile(str(self._last_output_dir)))

    def _on_progress(self, current: int, total: int, name: str):
        self.progress_bar.setMaximum(total)
        self.progress_bar.setValue(current)
        self.progress_bar.setFormat(f"Exporting {current}/{total}: {name}")

    def _on_log(self, message: str):
        self.log_view.append(message)

    def _on_finished(self, message: str, output_path: str):
        self._set_exporting(False)
        self.progress_bar.setFormat("Done")

        if output_path and Path(output_path).is_dir():
            self._last_output_dir = output_path
            self.open_folder_button.setEnabled(True)

        self.worker = None
        QMessageBox.information(self, "Export Complete", message)

    def _on_error(self, message: str):
        self._set_exporting(False)
        self.progress_bar.setFormat("Error")
        self.worker = None
        fallback = self.output_edit.text().strip()
        if fallback and Path(fallback).is_dir():
            self._last_output_dir = fallback
            self.open_folder_button.setEnabled(True)
        QMessageBox.critical(self, "Export Failed", message)

    def _set_exporting(self, exporting: bool):
        self.files_group.setEnabled(not exporting)
        self.output_group.setEnabled(not exporting)
        self.settings_group.setEnabled(not exporting)
        self.options_group.setEnabled(not exporting)
        self.export_button.setEnabled(not exporting)
        self.cancel_button.setEnabled(exporting)

    def _apply_styles(self):
        file = QFile(":/style.qss")
        if file.open(QIODevice.ReadOnly | QIODevice.Text):
            self.setStyleSheet(bytes(file.readAll()).decode("utf-8"))
            file.close()

    def closeEvent(self, event):
        if self.worker is not None and self.worker.isRunning():
            self.worker.cancel()
            if not self.worker.wait(5000):
                self.worker.terminate()
                self.worker.wait(1000)
        self.worker = None
        event.accept()


def main():
    app = QApplication(sys.argv)
    app.setStyle("Fusion")
    window = MainWindow()
    window.show()
    sys.exit(app.exec())


if __name__ == "__main__":
    main()